package com.philpot.nowplayinghistory.util

import com.philpot.nowplayinghistory.BuildConfig
import com.philpot.nowplayinghistory.db.dao.HistoryDao
import com.philpot.nowplayinghistory.db.dao.SongInfoDao
import com.philpot.nowplayinghistory.model.HistoryItem

/**
 * Created by MattPhilpot on 11/2/2017.
 */
object TestRecordInsertUtil {

    fun insertTestRecords(historyDao: HistoryDao) {
        if (BuildConfig.DEBUG) {
            /*
            if (historyDao.getCount() > 0) {
                return
            }
            */
            val insertList = mutableListOf<HistoryItem>()
            insertIntoList(insertList, "Caught Up in You", ".38 Special")
            insertIntoList(insertList, "Fantasy Girl", ".38 Special")
            insertIntoList(insertList, "Hold On Loosely", ".38 Special")
            insertIntoList(insertList, "Rockin' Into the Night", ".38 Special")
            insertIntoList(insertList, "Art For Arts Sake", "10cc")
            insertIntoList(insertList, "Kryptonite", "3 Doors Down")
            insertIntoList(insertList, "Loser", "3 Doors Down")
            insertIntoList(insertList, "When I'm Gone", "3 Doors Down")
            insertIntoList(insertList, "What's Up?", "4 Non Blondes")
            insertIntoList(insertList, "Take On Me", "a-ha")
            insertIntoList(insertList, "Baby, Please Don't Go", "AC/DC")
            insertIntoList(insertList, "Back In Black", "AC/DC")
            insertIntoList(insertList, "Big Gun", "AC/DC")
            insertIntoList(insertList, "CAN'T STOP ROCK'N'ROLL", "AC/DC")
            insertIntoList(insertList, "Dirty Deeds Done Dirt Cheap", "AC/DC")
            insertIntoList(insertList, "For Those About To Rock", "AC/DC")
            insertIntoList(insertList, "Girls Got Rhythm", "AC/DC")
            insertIntoList(insertList, "Hard As A Rock", "AC/DC")
            insertIntoList(insertList, "Have a Drink On Me", "AC/DC")
            insertIntoList(insertList, "Hells Bells", "AC/DC")
            insertIntoList(insertList, "Highway To Hell", "AC/DC")
            insertIntoList(insertList, "It's A Long Way To The Top", "AC/DC")
            insertIntoList(insertList, "Jailbreak", "AC/DC")
            insertIntoList(insertList, "Let There Be Rock", "AC/DC")
            insertIntoList(insertList, "Let's Get It Up", "AC/DC")
            insertIntoList(insertList, "Live Wire", "AC/DC")
            insertIntoList(insertList, "Moneytalks", "AC/DC")
            insertIntoList(insertList, "Night Prowler", "AC/DC")
            insertIntoList(insertList, "Rock and Roll Ain't Noise Pollution", "AC/DC")
            insertIntoList(insertList, "Shoot To Thrill", "AC/DC")
            insertIntoList(insertList, "Shot Down In Flames", "AC/DC")
            insertIntoList(insertList, "Sin City", "AC/DC")

            insertIntoList(insertList, "Caught Up in You", ".38 Special")

            insertIntoList(insertList, "T.N.T.", "AC/DC")
            insertIntoList(insertList, "Thunderstruck", "AC/DC")
            insertIntoList(insertList, "Touch Too Much", "AC/DC")
            insertIntoList(insertList, "What Do You Do For Money Honey", "AC/DC")
            insertIntoList(insertList, "Who Made Who", "AC/DC")
            insertIntoList(insertList, "Whole Lotta Rosie", "AC/DC")
            insertIntoList(insertList, "You Shook Me All Night Long", "AC/DC")
            insertIntoList(insertList, "How Long", "Ace")
            insertIntoList(insertList, "Dog On A Leash", "Adelitas Way")
            insertIntoList(insertList, "Angel", "Aerosmith")
            insertIntoList(insertList, "Baby, Please Don't Go", "Aerosmith")
            insertIntoList(insertList, "Back in the Saddle", "Aerosmith")
            insertIntoList(insertList, "Big Ten Inch", "Aerosmith")
            insertIntoList(insertList, "Come Together", "Aerosmith")
            insertIntoList(insertList, "Crazy", "Aerosmith")
            insertIntoList(insertList, "Cryin'", "Aerosmith")
            insertIntoList(insertList, "Draw The Line", "Aerosmith")
            insertIntoList(insertList, "Dream On", "Aerosmith")
            insertIntoList(insertList, "Dude (Looks Like a Lady)", "Aerosmith")
            insertIntoList(insertList, "Jaded", "Aerosmith")
            insertIntoList(insertList, "Janie's Got A Gun", "Aerosmith")
            insertIntoList(insertList, "Kings and Queens", "Aerosmith")
            insertIntoList(insertList, "Last Child", "Aerosmith")
            insertIntoList(insertList, "Let the Music Do the Talking", "Aerosmith")
            insertIntoList(insertList, "Livin' On The Edge", "Aerosmith")
            insertIntoList(insertList, "Love In An Elevator", "Aerosmith")
            insertIntoList(insertList, "Mama Kin", "Aerosmith")
            insertIntoList(insertList, "No More No More", "Aerosmith")
            insertIntoList(insertList, "One Way Street", "Aerosmith")
            insertIntoList(insertList, "Pink", "Aerosmith")
            insertIntoList(insertList, "Rag Doll", "Aerosmith")
            insertIntoList(insertList, "Same Old Song and Dance", "Aerosmith")
            insertIntoList(insertList, "Seasons of Wither", "Aerosmith")
            insertIntoList(insertList, "Sweet Emotion", "Aerosmith")
            insertIntoList(insertList, "The Other Side", "Aerosmith")
            insertIntoList(insertList, "Toys in the Attic", "Aerosmith")
            insertIntoList(insertList, "Train Kept A-Rollin'", "Aerosmith")
            insertIntoList(insertList, "Walk This Way", "Aerosmith")
            insertIntoList(insertList, "What It Takes", "Aerosmith")
            insertIntoList(insertList, "You See Me Crying", "Aerosmith")
            insertIntoList(insertList, "Hand In My Pocket", "Alanis Morissette")
            insertIntoList(insertList, "You Oughta Know", "Alanis Morissette")
            insertIntoList(insertList, "Black Velvet", "Alannah Myles")
            insertIntoList(insertList, "Fantasy", "Aldo Nova")
            insertIntoList(insertList, "BE MY LOVER", "Alice Cooper")
            insertIntoList(insertList, "Billion Dollar Babies", "Alice Cooper")
            insertIntoList(insertList, "Eighteen", "Alice Cooper")
            insertIntoList(insertList, "Elected", "Alice Cooper")
            insertIntoList(insertList, "House Of Fire", "Alice Cooper")
            insertIntoList(insertList, "I'm Eighteen", "Alice Cooper")
            insertIntoList(insertList, "No More Mr. Nice Guy", "Alice Cooper")
            insertIntoList(insertList, "School's Out", "Alice Cooper")
            insertIntoList(insertList, "Under My Wheels", "Alice Cooper")
            insertIntoList(insertList, "Welcome To My Nightmare", "Alice Cooper")
            insertIntoList(insertList, "Down in a Hole", "Alice In Chains")
            insertIntoList(insertList, "Man In The Box", "Alice In Chains")
            insertIntoList(insertList, "No Excuses", "Alice In Chains")
            insertIntoList(insertList, "Rooster", "Alice In Chains")
            insertIntoList(insertList, "Them Bones", "Alice In Chains")
            insertIntoList(insertList, "Would?", "Alice In Chains")
            insertIntoList(insertList, "Ain't Wastin' Time No More", "Allman Brothers Band")
            insertIntoList(insertList, "Blue Sky", "Allman Brothers Band")
            insertIntoList(insertList, "Good Clean Fun", "Allman Brothers Band")
            insertIntoList(insertList, "In Memory Of Elizabeth Reed", "Allman Brothers Band")
            insertIntoList(insertList, "Jessica", "Allman Brothers Band")
            insertIntoList(insertList, "Melissa", "Allman Brothers Band")
            insertIntoList(insertList, "Midnight Rider", "Allman Brothers Band")
            insertIntoList(insertList, "No One to Run With", "Allman Brothers Band")
            insertIntoList(insertList, "One Way Out", "Allman Brothers Band")
            insertIntoList(insertList, "Ramblin' Man", "Allman Brothers Band")
            insertIntoList(insertList, "Southbound", "Allman Brothers Band")
            insertIntoList(insertList, "Statesboro Blues", "Allman Brothers Band")
            insertIntoList(insertList, "Whippin' Post", "Allman Brothers Band")
            insertIntoList(insertList, "A Horse With No Name", "America")
            insertIntoList(insertList, "Sister Golden Hair", "America")
            insertIntoList(insertList, "Ventura Highway", "America")
            insertIntoList(insertList, "Caught Up in You", ".38 Special")

            insertIntoList(insertList, "Don't Bring Me Down", "Animals II")
            insertIntoList(insertList, "Don't Let Me Be Misunderstood", "Animals II")
            insertIntoList(insertList, "Immigrant Song", "Ann Wilson")
            insertIntoList(insertList, "Roller", "April Wine")
            insertIntoList(insertList, "Hold Your Head Up", "Argent")
            insertIntoList(insertList, "Coming into Los Angeles", "Arlo Guthrie")
            insertIntoList(insertList, "Wayside", "Artful Dodger")
            insertIntoList(insertList, "Heat of the Moment", "Asia")
            insertIntoList(insertList, "Only Time Will Tell", "Asia")
            insertIntoList(insertList, "So Into You", "Atlanta Rhythm Section")
            insertIntoList(insertList, "Spooky", "Atlanta Rhythm Section")
            insertIntoList(insertList, "Like a Stone", "Audioslave")
            insertIntoList(insertList, "Blondes In Black Cars", "Autograph")
            insertIntoList(insertList, "Turn Up the Radio", "Autograph")
            insertIntoList(insertList, "Rock And Roll Party In The Streets", "Axe")
            insertIntoList(insertList, "Let It Ride", "Bachman-Turner Overdrive")
            insertIntoList(insertList, "Roll On Down The Highway", "Bachman-Turner Overdrive")
            insertIntoList(insertList, "Takin' Care Of Business", "Bachman-Turner Overdrive")
            insertIntoList(insertList, "You Ain't Seen Nothin' Yet", "Bachman-Turner Overdrive")
            insertIntoList(insertList, "Bad Company", "Bad Company")
            insertIntoList(insertList, "Burnin' Sky", "Bad Company")
            insertIntoList(insertList, "Can't Get Enough", "Bad Company")
            insertIntoList(insertList, "Feel Like Makin' Love", "Bad Company")
            insertIntoList(insertList, "Gone Gone Gone", "Bad Company")
            insertIntoList(insertList, "Good Lovin' Gone Bad", "Bad Company")
            insertIntoList(insertList, "Movin' On", "Bad Company")
            insertIntoList(insertList, "Ready For Love", "Bad Company")
            insertIntoList(insertList, "Rock 'n' Roll Fantasy", "Bad Company")
            insertIntoList(insertList, "Rock Steady", "Bad Company")
            insertIntoList(insertList, "Run With The Pack", "Bad Company")
            insertIntoList(insertList, "Seagull", "Bad Company")
            insertIntoList(insertList, "Shooting Star", "Bad Company")
            insertIntoList(insertList, "Silver", "Blue And Gold")
            insertIntoList(insertList, "When I See You Smile", "Bad English")
            insertIntoList(insertList, "No Matter What", "Badfinger")
            insertIntoList(insertList, "Walks Like A Woman", "Baton Rouge")
            insertIntoList(insertList, "(You Gotta) Fight for Your Right (To Party)", "Beastie Boys")
            insertIntoList(insertList, "No Sleep Till Brooklyn", "Beastie Boys")
            insertIntoList(insertList, "Loser", "Beck")
            insertIntoList(insertList, "In a Big Country", "Big Country")
            insertIntoList(insertList, "Rock Around the Clock", "Bill Haley")
            insertIntoList(insertList, "AIN'T NO SUNSHINE", "Bill Withers")
            insertIntoList(insertList, "Cradle of Love", "Billy Idol")
            insertIntoList(insertList, "Dancing With Myself", "Billy Idol")
            insertIntoList(insertList, "Eyes Without a Face", "Billy Idol")
            insertIntoList(insertList, "Mony Mony", "Billy Idol")
            insertIntoList(insertList, "Rebel Yell", "Billy Idol")
            insertIntoList(insertList, "White Wedding", "Billy Idol")
            insertIntoList(insertList, "Allentown", "Billy Joel")
            insertIntoList(insertList, "Big Shot", "Billy Joel")
            insertIntoList(insertList, "Captain Jack", "Billy Joel")
            insertIntoList(insertList, "Don't Ask Me Why", "Billy Joel")
            insertIntoList(insertList, "Goodnight Saigon", "Billy Joel")
            insertIntoList(insertList, "It's Still Rock And Roll To Me", "Billy Joel")
            insertIntoList(insertList, "Miami 2017 {seen The Lights Go Out On Broadway} (live 1", "Billy Joel")
            insertIntoList(insertList, "Movin' Out (Anthony's Song)", "Billy Joel")
            insertIntoList(insertList, "My Life", "Billy Joel")
            insertIntoList(insertList, "New York State Of Mind", "Billy Joel")
            insertIntoList(insertList, "Only The Good Die Young", "Billy Joel")
            insertIntoList(insertList, "Piano Man", "Billy Joel")
            insertIntoList(insertList, "Prelude/angry Young Man", "Billy Joel")
            insertIntoList(insertList, "Scenes From An Italian Restaurant", "Billy Joel")
            insertIntoList(insertList, "SHE'S ALWAYS A WOMAN", "Billy Joel")
            insertIntoList(insertList, "Sometimes A Fantasy", "Billy Joel")
            insertIntoList(insertList, "The Ballad Of Billy The Kid", "Billy Joel")
            insertIntoList(insertList, "The Stranger", "Billy Joel")
            insertIntoList(insertList, "You May Be Right", "Billy Joel")
            insertIntoList(insertList, "Baby Come Back", "Billy Rankin")
            insertIntoList(insertList, "Everybody Wants You", "Billy Squier")
            insertIntoList(insertList, "In the Dark", "Billy Squier")
            insertIntoList(insertList, "Lonely Is the Night", "Billy Squier")
            insertIntoList(insertList, "My Kinda Lover", "Billy Squier")
            insertIntoList(insertList, "Rock Me Tonight", "Billy Squier")
            insertIntoList(insertList, "She's a Runner", "Billy Squier")
            insertIntoList(insertList, "The Stroke", "Billy Squier")
            insertIntoList(insertList, "Children Of The Sun", "Billy Thorpe")
            insertIntoList(insertList, "Fairies Wear Boots", "Black Sabbath")
            insertIntoList(insertList, "Heaven and Hell", "Black Sabbath")
            insertIntoList(insertList, "Iron Man", "Black Sabbath")
            insertIntoList(insertList, "N.i.b.", "Black Sabbath")
            insertIntoList(insertList, "Neon Knights", "Black Sabbath")
            insertIntoList(insertList, "Paranoid", "Black Sabbath")
            insertIntoList(insertList, "Sweet Leaf", "Black Sabbath")
            insertIntoList(insertList, "The Wizard", "Black Sabbath")
            insertIntoList(insertList, "War Pigs", "Black Sabbath")
            insertIntoList(insertList, "Highway Song", "Blackfoot")
            insertIntoList(insertList, "Train", "Train")
            insertIntoList(insertList, "Can't Find My Way Home", "Blind Faith")
            insertIntoList(insertList, "Presence of the Lord", "Blind Faith")
            insertIntoList(insertList, "No Rain", "Blind Melon")
            insertIntoList(insertList, "Presence of the Lord", "Blind Melon")
            insertIntoList(insertList, "All the Small Things", "Blink-182")
            insertIntoList(insertList, "Call Me", "Blondie")
            insertIntoList(insertList, "Heart of Glass", "Blondie")
            insertIntoList(insertList, "One Way Or Another", "Blondie")
            insertIntoList(insertList, "(Don't Fear) The Reaper", "Blue Oyster Cult")
            insertIntoList(insertList, "Bucks Boogie", "Blue Oyster Cult")
            insertIntoList(insertList, "Burnin' for You", "Blue Oyster Cult")
            insertIntoList(insertList, "Godzilla", "Blue Oyster Cult")
            insertIntoList(insertList, "I Love the Night", "Blue Oyster Cult")
            insertIntoList(insertList, "Summertime Blues", "Blue Oyster Cult")
            insertIntoList(insertList, "Song 2", "Blur")
            insertIntoList(insertList, "Just Like A Woman", "Bob Dylan")
            insertIntoList(insertList, "Knockin' On Heaven's Door", "Bob Dylan")
            insertIntoList(insertList, "Like a Rolling Stone", "Bob Dylan")
            insertIntoList(insertList, "Positively 4th Street", "Bob Dylan")
            insertIntoList(insertList, "Subterranean Homesick Blues", "Bob Dylan")
            insertIntoList(insertList, "Tangled Up In Blue", "Bob Dylan")
            insertIntoList(insertList, "Exodus", "Bob Marley")
            insertIntoList(insertList, "Jamming", "Bob Marley")
            insertIntoList(insertList, "No Woman", "No Cry")
            insertIntoList(insertList, "One Love", "Bob Marley")
            insertIntoList(insertList, "Stir It Up", "Bob Marley")
            insertIntoList(insertList, "Three Little Birds", "Bob Marley")
            insertIntoList(insertList, "Against The Wind", "Bob Seger")
            insertIntoList(insertList, "Betty Lou's Gettin' Out Tonigh", "Bob Seger")
            insertIntoList(insertList, "Come to Poppa", "Bob Seger")
            insertIntoList(insertList, "Feel Like a Number", "Bob Seger")
            insertIntoList(insertList, "Fire Down Below", "Bob Seger")
            insertIntoList(insertList, "Get Out of Denver", "Bob Seger")
            insertIntoList(insertList, "Her Strut", "Bob Seger")
            insertIntoList(insertList, "Hollywood Nights", "Bob Seger")
            insertIntoList(insertList, "Horizontal Bop", "Bob Seger")
            insertIntoList(insertList, "Katmandu", "Bob Seger")
            insertIntoList(insertList, "Mainstreet", "Bob Seger")
            insertIntoList(insertList, "Night Moves", "Bob Seger")
            insertIntoList(insertList, "Old Time Rock & Roll", "Bob Seger")
            insertIntoList(insertList, "Ramblin' Gamblin' Man", "Bob Seger")
            insertIntoList(insertList, "Rock And Roll Never Forgets", "Bob Seger")
            insertIntoList(insertList, "Roll Me Away", "Bob Seger")
            insertIntoList(insertList, "Still the Same", "Bob Seger")
            insertIntoList(insertList, "Sunspot Baby", "Bob Seger")
            insertIntoList(insertList, "The Fire Down Below", "Bob Seger")
            insertIntoList(insertList, "Travelin' Man", "Bob Seger")
            insertIntoList(insertList, "Turn On Your Love Light", "Bob Seger")
            insertIntoList(insertList, "Turn The Page", "Bob Seger")
            insertIntoList(insertList, "We've Got Tonite", "Bob Seger")
            insertIntoList(insertList, "You'll Accompany Me", "Bob Seger")
            insertIntoList(insertList, "Hypnotized", "Bob Welch")
            insertIntoList(insertList, "Bad Medicine", "Bon Jovi")
            insertIntoList(insertList, "Blaze of Glory", "Bon Jovi")
            insertIntoList(insertList, "Born To Be My Baby", "Bon Jovi")
            insertIntoList(insertList, "Lay Your Hands On Me", "Bon Jovi")
            insertIntoList(insertList, "Livin' On A Prayer", "Bon Jovi")
            insertIntoList(insertList, "Raise Your Hands", "Bon Jovi")
            insertIntoList(insertList, "Runaway", "Bon Jovi")
            insertIntoList(insertList, "She Don't Know Me", "Bon Jovi")
            insertIntoList(insertList, "Wanted Dead or Alive", "Bon Jovi")
            insertIntoList(insertList, "You Give Love A Bad Name", "Bon Jovi")
            insertIntoList(insertList, "Wait For You", "Bonham")
            insertIntoList(insertList, "Green Onions", "Booker T. and the MG's")
            insertIntoList(insertList, "A Man I'll Never Be", "Boston")
            insertIntoList(insertList, "Amanda", "Boston")
            insertIntoList(insertList, "Cool The Engines", "Boston")
            insertIntoList(insertList, "Don't Look Back", "Boston")
            insertIntoList(insertList, "Feelin' Satisfied", "Boston")
            insertIntoList(insertList, "Foreplay (Long Time)", "Boston")
            insertIntoList(insertList, "Hitch A Ride", "Boston")
            insertIntoList(insertList, "Let Me Take You Home Tonight", "Boston")
            insertIntoList(insertList, "More Than a Feeling", "Boston")
            insertIntoList(insertList, "Party", "Boston")
            insertIntoList(insertList, "Peace of Mind", "Boston")
            insertIntoList(insertList, "Rock & Roll Band", "Boston")
            insertIntoList(insertList, "Smokin'", "Boston")
            insertIntoList(insertList, "Something About You", "Boston")
            insertIntoList(insertList, "The Journey/It's Easy", "Boston")
            insertIntoList(insertList, "Used To Bad News", "Boston")
            insertIntoList(insertList, "We're Ready", "Boston")
            insertIntoList(insertList, "Lido Shuffle", "Boz Scaggs")
            insertIntoList(insertList, "Lowdown", "Boz Scaggs")
            insertIntoList(insertList, "Tarkio Road", "Brewer & Shipley")
            insertIntoList(insertList, "The Way It Is", "Bruce Hornsby & The Range")
            insertIntoList(insertList, "Atlantic City", "Bruce Springsteen")
            insertIntoList(insertList, "Backstreets", "Bruce Springsteen")
            insertIntoList(insertList, "Badlands", "Bruce Springsteen")
            insertIntoList(insertList, "Blinded By the Light", "Bruce Springsteen")
            insertIntoList(insertList, "Born In the U.S.A.", "Bruce Springsteen")
            insertIntoList(insertList, "Born To Run", "Bruce Springsteen")
            insertIntoList(insertList, "Cover Me", "Bruce Springsteen")
            insertIntoList(insertList, "Dancing In the Dark", "Bruce Springsteen")
            insertIntoList(insertList, "Glory Days", "Bruce Springsteen")
            insertIntoList(insertList, "Growin' Up", "Bruce Springsteen")
            insertIntoList(insertList, "Hungry Heart", "Bruce Springsteen")
            insertIntoList(insertList, "I'm On Fire", "Bruce Springsteen")
            insertIntoList(insertList, "It's Hard to Be a Saint in the City", "Bruce Springsteen")
            insertIntoList(insertList, "Jersey Girl", "Bruce Springsteen")
            insertIntoList(insertList, "Jungleland", "Bruce Springsteen")
            insertIntoList(insertList, "Pink Cadillac", "Bruce Springsteen")
            insertIntoList(insertList, "Prove It All Night", "Bruce Springsteen")
            insertIntoList(insertList, "Racing in the Streets", "Bruce Springsteen")
            insertIntoList(insertList, "Rosalita (Come Out Tonight)", "Bruce Springsteen")
            insertIntoList(insertList, "She's The One", "Bruce Springsteen")
            insertIntoList(insertList, "Spirit In The Night", "Bruce Springsteen")
            insertIntoList(insertList, "Tenth Avenue Freeze-Out", "Bruce Springsteen")
            insertIntoList(insertList, "Thunder Road", "Bruce Springsteen")
            insertIntoList(insertList, "Cuts Like a Knife", "Bryan Adams")
            insertIntoList(insertList, "Heaven", "Bryan Adams")
            insertIntoList(insertList, "Run to You", "Bryan Adams")
            insertIntoList(insertList, "Somebody", "Bryan Adams")
            insertIntoList(insertList, "Summer Of '69", "Bryan Adams")
            insertIntoList(insertList, "Sorry", "Buckcherry")
            insertIntoList(insertList, "For What It's Worth", "Buffalo Springfield")
            insertIntoList(insertList, "Mr. Soul", "Buffalo Springfield")
            insertIntoList(insertList, "Rock & Roll Woman", "Buffalo Springfield")
            insertIntoList(insertList, "Comedown", "Bush")
            insertIntoList(insertList, "Machinehead", "Bush")
            insertIntoList(insertList, "Far Behind", "Candlebox")
            insertIntoList(insertList, "Goin' up the Country", "Canned Heat")
            insertIntoList(insertList, "On the Road Again", "Canned Heat")
            insertIntoList(insertList, "IT'S TOO LATE", "Carole King")
            insertIntoList(insertList, "Oh Very Young", "Cat Stevens")
            insertIntoList(insertList, "WILD WORLD", "Cat Stevens")
            insertIntoList(insertList, "In America", "Charlie Daniels Band")
            insertIntoList(insertList, "Long Haired Country Boy", "Charlie Daniels Band")
            insertIntoList(insertList, "The Devil Went Down To Georgia", "Charlie Daniels Band")
            insertIntoList(insertList, "The Legend Of Wooley Swamp", "Charlie Daniels Band")
            insertIntoList(insertList, "The South's Gonna Do It Again", "Charlie Daniels Band")
            insertIntoList(insertList, "Uneasy Rider", "Charlie Daniels Band")
            insertIntoList(insertList, "Ain't That a Shame", "Cheap Trick")
            insertIntoList(insertList, "Dream Police", "Cheap Trick")
            insertIntoList(insertList, "I Want You to Want Me", "Cheap Trick")
            insertIntoList(insertList, "She's Tight", "Cheap Trick")
            insertIntoList(insertList, "Surrender", "Cheap Trick")
            insertIntoList(insertList, "Take Out The Gunman", "Chevelle")
            insertIntoList(insertList, "25 Or 6 To 4", "Chicago")
            insertIntoList(insertList, "Beginnings", "Chicago")
            insertIntoList(insertList, "Feeling Stronger Every", "Chicago")
            insertIntoList(insertList, "I'm a Man", "Chicago")
            insertIntoList(insertList, "JUST YOU AND ME", "Chicago")
            insertIntoList(insertList, "Make Me Smile", "Chicago")
            insertIntoList(insertList, "Questions 67 and 68", "Chicago")
            insertIntoList(insertList, "Saturday In the Park", "Chicago")
            insertIntoList(insertList, "South California Purples", "Chicago")
            insertIntoList(insertList, "JOHNNY B. GOODE", "Chuck Berry")
            insertIntoList(insertList, "Coming Home", "Cinderella")
            insertIntoList(insertList, "Don't Know What You Got", "Cinderella")
            insertIntoList(insertList, "Gypsy Road", "Cinderella")
            insertIntoList(insertList, "Nobody's Fool", "Cinderella")
            insertIntoList(insertList, "Somebody Save Me", "Cinderella")
            insertIntoList(insertList, "Better Off Without You", "Clarks")
            insertIntoList(insertList, "Born Too Late", "Clarks")
            insertIntoList(insertList, "Cigarette", "Clarks")
            insertIntoList(insertList, "Hey You", "Clarks")
            insertIntoList(insertList, "Maybe", "Clarks")
            insertIntoList(insertList, "Penny On The Floor", "Clarks")
            insertIntoList(insertList, "The River", "Clarks")
            insertIntoList(insertList, "December", "Collective Soul")
            insertIntoList(insertList, "Shine", "Collective Soul")
            insertIntoList(insertList, "The World I Know", "Collective Soul")
            insertIntoList(insertList, "Hot Rod Lincoln", "Commander Cody")
            insertIntoList(insertList, "Monkey Bars", "Coney Hatch")
            insertIntoList(insertList, "Mr. Jones", "Counting Crows")
            insertIntoList(insertList, "Low", "Cracker")
            insertIntoList(insertList, "Badge", "Cream")
            insertIntoList(insertList, "Born Under A Bad Sign", "Cream")
            insertIntoList(insertList, "Crossroads", "Cream")
            insertIntoList(insertList, "I'm So Glad", "Cream")
            insertIntoList(insertList, "Sunshine of Your Love", "Cream")
            insertIntoList(insertList, "Tales Of Brave Ulysses", "Cream")
            insertIntoList(insertList, "White Room", "Cream")
            insertIntoList(insertList, "Higher", "Creed")
            insertIntoList(insertList, "My Sacrifice", "Creed")
            insertIntoList(insertList, "With Arms Wide Open", "Creed")
            insertIntoList(insertList, "Bad Moon Rising", "Creedence Clearwater Revival")
            insertIntoList(insertList, "Born On the Bayou", "Creedence Clearwater Revival")
            insertIntoList(insertList, "Commotion", "Creedence Clearwater Revival")
            insertIntoList(insertList, "Down On the Corner", "Creedence Clearwater Revival")
            insertIntoList(insertList, "Fortunate Son", "Creedence Clearwater Revival")
            insertIntoList(insertList, "Green River", "Creedence Clearwater Revival")
            insertIntoList(insertList, "Have You Ever Seen the Rain?", "Creedence Clearwater Revival")
            insertIntoList(insertList, "I Heard It Through the Grapevine", "Creedence Clearwater Revival")
            insertIntoList(insertList, "Lodi", "Creedence Clearwater Revival")
            insertIntoList(insertList, "Lookin' Out My Back Door", "Creedence Clearwater Revival")
            insertIntoList(insertList, "Proud Mary", "Creedence Clearwater Revival")
            insertIntoList(insertList, "Run Through the Jungle", "Creedence Clearwater Revival")
            insertIntoList(insertList, "Suzie Q", "Creedence Clearwater Revival")
            insertIntoList(insertList, "Sweet Hitch Hiker", "Creedence Clearwater Revival")
            insertIntoList(insertList, "The Midnight Special", "Creedence Clearwater Revival")
            insertIntoList(insertList, "Travelin' Band", "Creedence Clearwater Revival")
            insertIntoList(insertList, "Up Around the Bend", "Creedence Clearwater Revival")
            insertIntoList(insertList, "Who'll Stop the Rain", "Creedence Clearwater Revival")
            insertIntoList(insertList, "Fire Woman", "Crosby, Stills & Nash")
            insertIntoList(insertList, "Helplessly Hoping", "Crosby, Stills & Nash")
            insertIntoList(insertList, "Long Time Gone", "Crosby, Stills & Nash")
            insertIntoList(insertList, "Southern Cross", "Crosby, Stills & Nash")
            insertIntoList(insertList, "Suite: Judy Blue Eyes", "Crosby, Stills & Nash")
            insertIntoList(insertList, "Carry On", "Crosby, Stills, Nash & Young")
            insertIntoList(insertList, "Ohio", "Crosby, Stills, Nash & Young")
            insertIntoList(insertList, "Woodstock", "Crosby, Stills, Nash & Young")
            insertIntoList(insertList, "(I Just) Died in Your Arms", "Cutting Crew")
            insertIntoList(insertList, "High Enough", "Damn Yankees")
            insertIntoList(insertList, "I HEAR YOU KNOCKING", "Dave Edmunds")
            insertIntoList(insertList, "Headkeeper", "Dave Mason")
            insertIntoList(insertList, "Only You Know And I Know", "Dave Mason")
            insertIntoList(insertList, "We Just Disagree", "Dave Mason")
            insertIntoList(insertList, "Welcome To The Boomtown", "David & David")
            insertIntoList(insertList, "Changes", "David Bowie")
            insertIntoList(insertList, "China Girl", "David Bowie")
            insertIntoList(insertList, "Diamond Dogs", "David Bowie")
            insertIntoList(insertList, "Fame", "David Bowie")
            insertIntoList(insertList, "Fashion", "David Bowie")
            insertIntoList(insertList, "Friday on My Mind", "David Bowie")
            insertIntoList(insertList, "Golden Years", "David Bowie")
            insertIntoList(insertList, "Heroes", "David Bowie")
            insertIntoList(insertList, "Jean Genie", "David Bowie")
            insertIntoList(insertList, "Let's Dance", "David Bowie")
            insertIntoList(insertList, "Modern Love", "David Bowie")
            insertIntoList(insertList, "Panic in Detroit", "David Bowie")
            insertIntoList(insertList, "Rebel Rebel", "David Bowie")
            insertIntoList(insertList, "Space Oddity", "David Bowie")
            insertIntoList(insertList, "Starman", "David Bowie")
            insertIntoList(insertList, "Stay", "David Bowie")
            insertIntoList(insertList, "Suffragette City", "David Bowie")
            insertIntoList(insertList, "Young Americans", "David Bowie")
            insertIntoList(insertList, "Ziggy Stardust", "David Bowie")
            insertIntoList(insertList, "Rock On", "David Essex")
            insertIntoList(insertList, "There's No Way Out Of Here", "David Essex")
            insertIntoList(insertList, "There's No Way Out Of Here", "David Gilmour")
            insertIntoList(insertList, "Frenchette", "David Johansen")
            insertIntoList(insertList, "California Girls", "David Lee Roth")
            insertIntoList(insertList, "Just A Gigolo / I Ain't Got Nobody", "David Lee Roth")
            insertIntoList(insertList, "Yankee Rose", "David Lee Roth")
            insertIntoList(insertList, "Burn", "Deep Purple")
            insertIntoList(insertList, "Child In Time", "Deep Purple")
            insertIntoList(insertList, "Highway Star", "Deep Purple")
            insertIntoList(insertList, "Hush", "Deep Purple")
            insertIntoList(insertList, "Kentucky Woman", "Deep Purple")
            insertIntoList(insertList, "Knocking At Your Backdoo", "Deep Purple")
            insertIntoList(insertList, "Lazy", "Deep Purple")
            insertIntoList(insertList, "Perfect Strangers", "Deep Purple")
            insertIntoList(insertList, "Smoke On The Water", "Deep Purple")
            insertIntoList(insertList, "Space Truckin'", "Deep Purple")
            insertIntoList(insertList, "Woman From Tokyo", "Deep Purple")
            insertIntoList(insertList, "Animal", "Def Leppard")
            insertIntoList(insertList, "Armageddon It", "Def Leppard")
            insertIntoList(insertList, "Bringin' On The Heartbreak", "Def Leppard")
            insertIntoList(insertList, "Foolin'", "Def Leppard")
            insertIntoList(insertList, "Hysteria", "Def Leppard")
            insertIntoList(insertList, "Love Bites", "Def Leppard")
            insertIntoList(insertList, "On Through The Night", "Def Leppard")
            insertIntoList(insertList, "Photograph", "Def Leppard")
            insertIntoList(insertList, "Pour Some Sugar On Me", "Def Leppard")
            insertIntoList(insertList, "Rock of Ages", "Def Leppard")
            insertIntoList(insertList, "Rock Rock", "Def Leppard")
            insertIntoList(insertList, "Rocket", "Def Leppard")
            insertIntoList(insertList, "Too Late for Love", "Def Leppard")
            insertIntoList(insertList, "Enjoy the Silence", "Depeche Mode")
            insertIntoList(insertList, "Bell Bottom Blues", "Derek & The Dominos")
            insertIntoList(insertList, "Have You Ever Loved a Woman", "Derek & The Dominos")
            insertIntoList(insertList, "Layla", "Derek & The Dominos")
            insertIntoList(insertList, "Recognition", "Detective")
            insertIntoList(insertList, "ANGELOS", "Dick Siegel")
            insertIntoList(insertList, "Holy Diver", "Dio")
            insertIntoList(insertList, "Rainbow In the Dark", "Dio")
            insertIntoList(insertList, "The Last In Line", "Dio")
            insertIntoList(insertList, "Brothers In Arms", "Dire Straits")
            insertIntoList(insertList, "Down To The Waterline", "Dire Straits")
            insertIntoList(insertList, "Expresso Love", "Dire Straits")
            insertIntoList(insertList, "Industrial Disease", "Dire Straits")
            insertIntoList(insertList, "Lady Writer", "Dire Straits")
            insertIntoList(insertList, "Money for Nothing", "Dire Straits")
            insertIntoList(insertList, "Romeo And Juliet", "Dire Straits")
            insertIntoList(insertList, "So Far Away", "Dire Straits")
            insertIntoList(insertList, "Solid Rock", "Dire Straits")
            insertIntoList(insertList, "Sultans of Swing", "Dire Straits")
            insertIntoList(insertList, "Walk of Life", "Dire Straits")
            insertIntoList(insertList, "Counting Blue Cars", "Dishwalla")
            insertIntoList(insertList, "Drift Away", "Dobie Gray")
            insertIntoList(insertList, "Alone Again", "Dokken")
            insertIntoList(insertList, "In My Dreams", "Dokken")
            insertIntoList(insertList, "Into The Fire", "Dokken")
            insertIntoList(insertList, "Heavy Metal", "Don Felder")
            insertIntoList(insertList, "All She Wants to Do Is Dance", "Don Henley")
            insertIntoList(insertList, "Dirty Laundry", "Don Henley")
            insertIntoList(insertList, "Sunset Grill", "Don Henley")
            insertIntoList(insertList, "The Boys Of Summer", "Don Henley")
            insertIntoList(insertList, "The Heart of the Matter", "Don Henley")
            insertIntoList(insertList, "The Last Worthless Evening", "Don Henley")
            insertIntoList(insertList, "American Pie", "Don McLean")
            insertIntoList(insertList, "Ah! Leah!", "Donnie Iris")
            insertIntoList(insertList, "Love Is Like A Rock", "Donnie Iris")
            insertIntoList(insertList, "Season of the Witch", "Donovan")
            insertIntoList(insertList, "Sunshine Superman", "Donovan")
            insertIntoList(insertList, "COVER OF THE ROLLING STONE", "Dr. Hook & the Medicine Show")
            insertIntoList(insertList, "Right Place Wrong Time", "Dr. John")
            insertIntoList(insertList, "Anything", "Anything")
            insertIntoList(insertList, "Hey", "Hey (What Can I Do?)")
            insertIntoList(insertList, "Rio", "Duran Duran")
            insertIntoList(insertList, "Already Gone", "Eagles")
            insertIntoList(insertList, "Desperado", "Eagles")
            insertIntoList(insertList, "Heartache Tonight", "Eagles")
            insertIntoList(insertList, "Hotel California", "Eagles")
            insertIntoList(insertList, "I Can't Tell You Why", "Eagles")
            insertIntoList(insertList, "In The City", "Eagles")
            insertIntoList(insertList, "Life in the Fast Lane", "Eagles")
            insertIntoList(insertList, "Lyin' Eyes", "Eagles")
            insertIntoList(insertList, "New Kid In Town", "Eagles")
            insertIntoList(insertList, "One of These Nights", "Eagles")
            insertIntoList(insertList, "Peaceful Easy Feeling", "Eagles")
            insertIntoList(insertList, "Seven Bridges Road", "Eagles")
            insertIntoList(insertList, "Take It Easy", "Eagles")
            insertIntoList(insertList, "Take It to the Limit", "Eagles")
            insertIntoList(insertList, "Tequila Sunrise", "Eagles")
            insertIntoList(insertList, "The Best of My Love", "Eagles")
            insertIntoList(insertList, "The Long Run", "Eagles")
            insertIntoList(insertList, "Those Shoes", "Eagles")
            insertIntoList(insertList, "Victim of Love", "Eagles")
            insertIntoList(insertList, "Witchy Woman", "Eagles")
            insertIntoList(insertList, "Baby Hold On", "Eddie Money")
            insertIntoList(insertList, "Gimme Some Water", "Eddie Money")
            insertIntoList(insertList, "Shakin'", "Eddie Money")
            insertIntoList(insertList, "Take Me Home Tonight", "Eddie Money")
            insertIntoList(insertList, "Think I'm In Love", "Eddie Money")
            insertIntoList(insertList, "Two Tickets To Paradise", "Eddie Money")
            insertIntoList(insertList, "Frankenstein", "Edgar Winter Group")
            insertIntoList(insertList, "Free Ride", "Edgar Winter Group")
            insertIntoList(insertList, "WAR", "Edwin Starr")
            insertIntoList(insertList, "CAN'T GET IT OUT OF MY HEAD", "Electric Light Orchestra")
            insertIntoList(insertList, "Do Ya", "Electric Light Orchestra")
            insertIntoList(insertList, "Don't Bring Me Down", "Electric Light Orchestra")
            insertIntoList(insertList, "Evil Woman", "Electric Light Orchestra")
            insertIntoList(insertList, "Fire On High", "Electric Light Orchestra")
            insertIntoList(insertList, "Livin' Thing", "Electric Light Orchestra")
            insertIntoList(insertList, "Roll Over Beethoven", "Electric Light Orchestra")
            insertIntoList(insertList, "Strange Magic", "Electric Light Orchestra")
            insertIntoList(insertList, "Sweet Talkin' Woman", "Electric Light Orchestra")
            insertIntoList(insertList, "Telephone Line", "Electric Light Orchestra")
            insertIntoList(insertList, "Turn To Stone", "Electric Light Orchestra")
            insertIntoList(insertList, "All The Girls Love Alice", "Elton John")
            insertIntoList(insertList, "Bennie And The Jets", "Elton John")
            insertIntoList(insertList, "Candle in the Wind", "Elton John")
            insertIntoList(insertList, "Captain Fantastic", "Elton John")
            insertIntoList(insertList, "Crocodile Rock", "Elton John")
            insertIntoList(insertList, "DANIEL", "Elton John")
            insertIntoList(insertList, "Don't Let The Sun Go Down On Me", "Elton John")
            insertIntoList(insertList, "Funeral for a Friend (Love Lies Bleeding)", "Elton John")
            insertIntoList(insertList, "Goodbye Yellow Brick Road", "Elton John")
            insertIntoList(insertList, "Harmony", "Elton John")
            insertIntoList(insertList, "Honky Cat", "Elton John")
            insertIntoList(insertList, "Levon", "Elton John")
            insertIntoList(insertList, "Madman Across The Water", "Elton John")
            insertIntoList(insertList, "Rocket Man", "Elton John")
            insertIntoList(insertList, "Saturday Night's Alright for Fighting", "Elton John")
            insertIntoList(insertList, "Someone Saved My Life Tonight", "Elton John")
            insertIntoList(insertList, "Take Me to the Pilot", "Elton John")
            insertIntoList(insertList, "Teacher I Need You", "Elton John")
            insertIntoList(insertList, "THE BITCH IS BACK", "Elton John")
            insertIntoList(insertList, "Tiny Dancer", "Elton John")
            insertIntoList(insertList, "Where To Now St. Peter", "Elton John")
            insertIntoList(insertList, "Your Song", "Elton John")
            insertIntoList(insertList, "Fooled around and Fell in Love", "Elvin Bishop")
            insertIntoList(insertList, "Alison", "Elvis Costello")
            insertIntoList(insertList, "Pump It Up", "Elvis Costello")
            insertIntoList(insertList, "Veronica", "Elvis Costello")
            insertIntoList(insertList, "From the Beginning", "Emerson, Lake & Palmer")
            insertIntoList(insertList, "Hoedown", "Emerson, Lake & Palmer")
            insertIntoList(insertList, "Karn Evil 9", "Emerson, Lake & Palmer")
            insertIntoList(insertList, "Lucky Man", "Emerson, Lake & Palmer")
            insertIntoList(insertList, "Still You Turn Me On", "Emerson, Lake & Palmer")
            insertIntoList(insertList, "After Midnight", "Eric Clapton")
            insertIntoList(insertList, "Bad Love", "Eric Clapton")
            insertIntoList(insertList, "Call Me the Breeze", "Eric Clapton")
            insertIntoList(insertList, "Cocaine", "Eric Clapton")
            insertIntoList(insertList, "Don't Think Twice", "It's Alright")
            insertIntoList(insertList, "Forever Man", "Eric Clapton")
            insertIntoList(insertList, "I Can't Stand It", "Eric Clapton")
            insertIntoList(insertList, "I Shot The Sheriff", "Eric Clapton")
            insertIntoList(insertList, "I've Got a Rock 'N' Roll Heart", "Eric Clapton")
            insertIntoList(insertList, "It's In The Way That You Use It", "Eric Clapton")
            insertIntoList(insertList, "Knockin' On Heaven's Door", "Eric Clapton")
            insertIntoList(insertList, "Lay Down Sally", "Eric Clapton")
            insertIntoList(insertList, "Layla", "Eric Clapton")
            insertIntoList(insertList, "Let It Grow", "Eric Clapton")
            insertIntoList(insertList, "Let It Rain", "Eric Clapton")
            insertIntoList(insertList, "Pretending", "Eric Clapton")
            insertIntoList(insertList, "She's Waiting", "Eric Clapton")
            insertIntoList(insertList, "Tears In Heaven", "Eric Clapton")
            insertIntoList(insertList, "The Core", "Eric Clapton")
            insertIntoList(insertList, "Willie and the Hand Jive", "Eric Clapton")
            insertIntoList(insertList, "Wonderful Tonight", "Eric Clapton")
            insertIntoList(insertList, "Cliffs Of Dover", "Eric Johnson")
            insertIntoList(insertList, "The Final Countdown", "Europe")
            insertIntoList(insertList, "Sweet Dreams (Are Made of This)", "Eurythmics")
            insertIntoList(insertList, "Inside Out", "Eve 6")
            insertIntoList(insertList, "Santa Monica", "Everclear")
            insertIntoList(insertList, "The Boys Are Back In Town", "Everclear")
            insertIntoList(insertList, "What It's Like", "Everlast")
            insertIntoList(insertList, "More Than Words", "Extreme")
            insertIntoList(insertList, "Mutha (Don't Wanna Go To School Today)", "Extreme")
            insertIntoList(insertList, "Ooh La La", "Faces")
            insertIntoList(insertList, "Stay With Me", "Faces")
            insertIntoList(insertList, "Epic", "Faith No More")
            insertIntoList(insertList, "House Of Pain", "Faster Pussycat")
            insertIntoList(insertList, "All The Kings Horses", "Firm")
            insertIntoList(insertList, "Signs", "Five Man Electrical Band")
            insertIntoList(insertList, "Blue Letter", "Fleetwood Mac")
            insertIntoList(insertList, "Don't Stop", "Fleetwood Mac")
            insertIntoList(insertList, "Dreams", "Fleetwood Mac")
            insertIntoList(insertList, "Go Your Own Way", "Fleetwood Mac")
            insertIntoList(insertList, "Gold Dust Woman", "Fleetwood Mac")
            insertIntoList(insertList, "Gypsy", "Fleetwood Mac")
            insertIntoList(insertList, "Hold Me", "Fleetwood Mac")
            insertIntoList(insertList, "Hypnotized", "Fleetwood Mac")
            insertIntoList(insertList, "I Don't Want To Know", "Fleetwood Mac")
            insertIntoList(insertList, "I'm So Afraid", "Fleetwood Mac")
            insertIntoList(insertList, "Landslide", "Fleetwood Mac")
            insertIntoList(insertList, "Little Lies", "Fleetwood Mac")
            insertIntoList(insertList, "Monday Morning", "Fleetwood Mac")
            insertIntoList(insertList, "Never Going Back Again", "Fleetwood Mac")
            insertIntoList(insertList, "Oh Well", "Fleetwood Mac")
            insertIntoList(insertList, "Rhiannon", "Fleetwood Mac")
            insertIntoList(insertList, "Sara", "Fleetwood Mac")
            insertIntoList(insertList, "Say You Love Me", "Fleetwood Mac")
            insertIntoList(insertList, "Second Hand News", "Fleetwood Mac")
            insertIntoList(insertList, "Sentimental Lady", "Fleetwood Mac")
            insertIntoList(insertList, "The Chain", "Fleetwood Mac")
            insertIntoList(insertList, "Tusk", "Fleetwood Mac")
            insertIntoList(insertList, "World Turning", "Fleetwood Mac")
            insertIntoList(insertList, "You Make Loving Fun", "Fleetwood Mac")

            historyDao.insertOrUpdateAll(insertList)
        }
    }
    
    private fun getBackdatedTimestamp(timestamp: Long?): Long {
        timestamp?.let { 
            return it - 3000000
        }
        return System.currentTimeMillis()
    }
    
    private fun insertIntoList(list: MutableList<HistoryItem>, title: String, artist: String) {
        val previous = list.lastOrNull()
        val newItem = HistoryItem(title = title, artist = artist, timestamp = getBackdatedTimestamp(previous?.timestamp))
        list.add(newItem)
    } 

    fun insertNewRandomRecord(historyDao: HistoryDao, songInfoDao: SongInfoDao) {
        val item = historyDao.getAll()[(historyDao.getCount() / 2) + 1]
        item.timestamp = System.currentTimeMillis()
        if (historyDao.insertIfNotRepeat(item)) {
            songInfoDao.updateLastHeard(item)
        }
    }
}